author = Marion Niesen
email = sjneisen@madiosncollege.edu
course = Advanced Java

driver = org.mariadb.jdbc.Driver
url = jdbc:mariadb://localhost/student?serverTimezone=America/Chicago
username = student
password = student