myName = Marion Niesen
myEmail = sjniesen@madisoncollege.edu
courseTitle = Advanced Java Programming

driver = org.mariadb.jdbc.Driver
url = jdbc:mariadb://localhost/student?serverTimezone=America/Chicago

username = student
password = student