my.name = Marion Niesen
my.email = sjniesen@madisoncollege.edu

course.title = Advanced Java Programming
course.meeting.times = Monday, Wednesday: 2:30-4:10
course.professor = Kari Schumacher

multi.line.description = this is \
                        a multi-line \
                        property!
